
namespace Organization.Shared.Identity;

/// <summary>
/// Request model for completing a WebAuthn authentication ceremony.
/// </summary>
public class WebAuthAuthenticateCompleteRequest
{
    /// <summary>
    /// The email address of the authenticating user.
    /// </summary>
    [Required(ErrorMessage = "Email is required.")]
    public string Email { get; set; } = string.Empty;

    /// <summary>
    /// The credential identifier being used for authentication.
    /// </summary>
    [Required(ErrorMessage = "Credential ID is required.")]
    public string CredentialId { get; set; } = string.Empty;

    /// <summary>
    /// The client data JSON containing the challenge and origin information.
    /// </summary>
    [Required(ErrorMessage = "Client data JSON is required.")]
    public string ClientDataJson { get; set; } = string.Empty;

    /// <summary>
    /// The authenticator data from the WebAuthn response.
    /// </summary>
    [Required(ErrorMessage = "Authenticator data is required.")]
    public string AuthenticatorData { get; set; } = string.Empty;

    /// <summary>
    /// The digital signature generated by the authenticator.
    /// </summary>
    [Required(ErrorMessage = "Signature is required.")]
    public string Signature { get; set; } = string.Empty;

    /// <summary>
    /// Optional user handle from the authenticator.
    /// </summary>
    public string? UserHandle { get; set; }
}
