
namespace Organization.Shared.Identity;

/// <summary>
/// Result model containing WebAuthn authentication data from the client.
/// </summary>
public class WebAuthAuthenticateClientResult
{
    /// <summary>
    /// The credential identifier used for authentication.
    /// </summary>
    public string CredentialId { get; set; } = string.Empty;

    /// <summary>
    /// The client data JSON containing the challenge and origin information.
    /// </summary>
    public string ClientDataJson { get; set; } = string.Empty;

    /// <summary>
    /// The authenticator data from the WebAuthn response.
    /// </summary>
    public string AuthenticatorData { get; set; } = string.Empty;

    /// <summary>
    /// The digital signature generated by the authenticator.
    /// </summary>
    public string Signature { get; set; } = string.Empty;

    /// <summary>
    /// Optional user handle from the authenticator.
    /// </summary>
    public string? UserHandle { get; set; }
}
